### ISSUE TITLE
How Exactly Is It Used and What Does It Do?

### ISSUE THREAD

**Issue by ersincaki** [DustyIdeas/All-Patches#1]
I'm not a British citizen, so I don't speak English. I used Translate, but again it wasn't enough. What exactly does this plugin do? I downloaded it but I don't know how to use it. Why don't you make a tutorial video about it. It shouldn't be difficult to make a preview video.

**Comment by DustyIdeas** [comment]
Lütfen hangi eklentiden bahsettiğinizi netleştirebilir misiniz?
